#!/bin/sh

PIDFILE=/run/passkeeper.pid

start() {
    modprobe -a dwc2 
    mount -t configfs none /sys/kernel/config
    /root/service -d oled -c /root/.seedkeeper 2>&1 & >> /root/service.logs
    echo $! > "$PIDFILE"
}

stop() {
    kill `cat $PIDFILE`
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
